name: Build mdc0

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4.2.2
      
    - name: Make IPA
      run: ./ipabuild.sh

    - uses: actions/upload-artifact@v4.6.2
      with:
       name: IPA Download
       path: build/mdc0.ipa
