name: Build mdc0

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4.2.2
      
    - name: Make IPA
      run: ./ipabuild.sh

    - uses: actions/upload-artifact@v4.6.2
      with:
       name: IPA Download
       path: build/mdc0.ipa
